### ISSUE TITLE
Fresher look at extending DevTools

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#100]
A page should be added for guiding people in debugging their extensions. I think it should go under [the integrating](https://developer.chrome.com/devtools/docs/integrating) docs, so I'll start working on a page under that stuff.

Currently planning for: 
* How to inspect the dev tools

Since I haven't built any extensions yet, if there are any other common issues people have with debugging extensions please let me know so I can try to get it included.

**Comment by paulirish** [comment]
Garbee, feels like this one fell off. We have some open work around extensions so I'm going to round up it all and integrate this with the rest..

**Comment by Garbee** [comment]
Yea, this just hasn't been a big priority with everything else going on. Maybe re-asses this after we move tutorial information out and clean up the existing reference stuff.
