### ISSUE TITLE
Check for 404's and get them fixed

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#138]
Does anyone know of any tools for checking sites automatically for 404 errors routinely? I ran a check today using linkchecker and there are quite a few 404's on other resources (like a few [WPD](http://www.webplatform.org) links from their move.) I would like us to get a system for automatically checking for bad links in the devtool docs so we can stay on top of keeping things clean.

If a tool doesn't currently exist, then I can take a look into building one for us that can run once every few weeks and report any findings back.

**Comment by paulirish** [comment]
Just ran the site through http://validator.w3.org/checklink?uri=https%3A%2F%2Fdeveloper.chrome.com%2Fdevtools&hide_type=all&recursive=on&depth=&check=Check#results1  and processing results....

**Comment by paulirish** [comment]
fixed the local stuff and a few things on the chrome side. good for now!! :D
