### ISSUE TITLE
Shortcut for device mode

### ISSUE THREAD

**Issue by jaredwilli** [GoogleChrome/devtools-docs#171]
Need to add to shortcuts doc
Ctrl/Cmd + Shift + M - toggle device mode

https://twitter.com/addyosmani/status/517803780960563200

**Comment by gk2go** [comment]
The shortcut that we need is one that you can use without being in the developer mode. On any page press the shortcut and you can see how that page looks like from an iPhone 5.

**Comment by Garbee** [comment]
@gk2go since this is a developer tools feature you need to have it open to work. No extra shortcut will be provided outside of that.

**Comment by gk2go** [comment]
Ok, is it possible for me to create a Chrome extension that provides
this shortcut? That is, is it possible to invoke the device mode
programmatically?

-- 



Gabriele Kahlout

a.co/2Nmg8ML

**Comment by kdzwinel** [comment]
Yes, kind of, you can turn on emulation using DevTools debugging protocol (that Chrome extensions have access to). You won't be able to use DevTools in the same time though.

https://developer.chrome.com/extensions/debugger
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride
