### ISSUE TITLE
universal ADBdriver suggestion

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-docs#189]
We've had a few reports where the drivers from android fail people and the universal adb driver from koush (good guy) works well.

I think we should just simplify things for our windows users and recommend that.

https://github.com/koush/UniversalAdbDriver
http://developer.android.com/tools/extras/oem-usb.html#Drivers

what do yall think?

**Comment by Garbee** [comment]
I don't see any big issue with dropping in a note about Koush's drivers.

**Comment by paulirish** [comment]
I dont have easy access to a windows box so i can't validate that the UX of using his msi is better than the big android page of download links.

i tried once in a virtualbox and nothing worked. so. .. unclear! need more windows people.

**Comment by Garbee** [comment]
I can test it tomorrow. VBox probably had issues passing through the USB connection.

**Comment by Garbee** [comment]
Just tested with a few android devices against Chrome Canary for remote debugging, the open driver didn't work for any of the devices. :frowning:

So, we should just recommend getting the provided drivers for a given device (as I believe we currently do) and leave it at that.

**Comment by paulirish** [comment]
thanks for giving it a go.

**Comment by Garbee** [comment]
Actually, I'm going to look into this again on the current beta and stable channels. Looks like what I experienced could have been due to a possible [bug](https://code.google.com/p/chromium/issues/detail?id=450007) in the build I was using.

**Comment by Garbee** [comment]
Tested a little bit ago, still not functioning on a few devices I have.

**Comment by paulirish** [comment]
sgtm. thanks
