### ISSUE TITLE
Need to document what the number count is in console

### ISSUE THREAD

**Issue by jaredwilli** [GoogleChrome/devtools-docs#198]
[Reference on SO](http://stackoverflow.com/questions/27112211/identifying-feature-of-page-inspector-chrome)

Apparently this hasn't been documented yet so we should add it somewhere to help clarify what the numbers mean exactly.

![Image](http://i.stack.imgur.com/mGHuW.png)

**Comment by Garbee** [comment]
I think we should call this "Stacking". Since you are stacking consecutive log messages to keep the output more concise.

Any other name ideas? Or does one exist already and I just don't know?

**Comment by Garbee** [comment]
On cruise control for PR #251. Just going to close this up preemptively to keep the issues cleaner.
