### ISSUE TITLE
Update contributing guide

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-docs#199]

**Comment by paulirish** [comment]
ws query parameter
&experiments query parameter

**Comment by paulirish** [comment]
below, three methods of hacking on devtools:


## DevTools hacking for noobs.
##### pull only devtools frontend, no chromium compile

* Follow checkout procedure here: https://medium.com/@aslushnikov/hacking-chrome-devtools-8c8896f5cef3
* Load the frontend using https://chrome.google.com/webstore/detail/dev-tools-app/eichfopopofffkbhjgbabdegakcdmpkm?hl=en-US

## Intermediate DevTools Hacking
##### Full checkout, depot_tools, and a whole lot of detail 
https://developer.chrome.com/devtools/docs/contributing#contributing-to-devtools-source-code

## Professional DevTools hacking
##### Yes, this means building chromium.
#### [paul's guide to building chrome](https://gist.github.com/paulirish/2d84a6db1b41b4020685)
 updated (but not perfect. ). read the [readme](https://gist.github.com/paulirish/2d84a6db1b41b4020685#file-readme-md).

## Submitting changes

1. follow this stuff https://developer.chrome.com/devtools/docs/contributing#step-6-upload-your-patch
1. Don't use `--bypass-hooks` for anything but the most trivial of changes.
  * (use depot tools and java to get presubmit script running.)
  * run `
  * > During the presubmit check step, not only the code is checked for type consistency by the Closure compiler, but a number of other checks are run against the code, since the compiler is no silver bullet (as opposed to the Java and C++ compilers out there) and misses quite a few errors. So if your change is not an off-by-one error or a UI message typo fix, be sure to set up your environment properly and run the presubmit whenever you upload your changes (since the presubmit is NOT run on the bots during the commit step.)
  * > Provided that you have set up your checkout according to http://www.chromium.org/developers/how-tos/get-the-code and are still getting errors, please mail me directly, and I will do my best to help you get set up (in fact, you should only need depot_tools installed and a Java 7 executable found on your $PATH (or %PATH%) for the presubmit hooks to work properly.)


## notes

* If you need experiments to load in your frontend make sure `&experiments=true` is in the URL
* The `ws` query parameter defines the websocket connection. 
* The [debugger protocol](https://developer.chrome.com/devtools/docs/debugger-protocol) page is probably also helpful 


<hr> 

need to update the [real contributing page](https://developer.chrome.com/devtools/docs/contributing) with this.

**Comment by pbakaus** [comment]
This is great stuff! We definitely should make a page. I kind of wish we would only share one way of doing it though, for simplicity reasons.

I have a few scripts that dramatically improve many of the steps. Gave them to Max too, he seems to be pretty happy with it. The aliases the scripts give you are:

- "fresh" - updates WebKit and Chromium via rebase-update, does some other stuff
- "build" - builds Chromium with Devtools debug flag etc
- "chromium" - runs the compiled Chromium

**Comment by paulirish** [comment]
put your scripts up as a gist!

I think there has two be two paths.

First one is the uber-fast "let's just start hacking" front-end only route.
  (part two of that can incorporate submitting patches for review.)

The second path is building Chromiu

**Comment by pbakaus** [comment]
Enjoy: https://gist.github.com/pbakaus/73bead28ebcf43740eaa

IMO: There are too many things that are not supported when doing the hacky fast path, i.e. developing for Device Mode. But I hear ya, building Chromioum is a huge pain point if you don't have access to Goma and are on a slow machine.

**Comment by paulirish** [comment]
### A few advanced hacking notes on plumbing data
 browser through blink into devtools

#### The life of a raw header 

1. blink: requests to collect devtools-related info in Resource::setReportRawHeaders. It turns into a flag REPORT_RAW_HEADERS which enables network instrumentation in the browser
2. browser/content: content/browser/devtools/devtools_netlog_observer.cc, is listening to the network log and collects necessary data
3. browser/content: populates this info into content/public/common/resource_devtools_info.h (all per-request)
4. browser/content: DevTools info gets into child process: WebURLLoaderImpl::PopulateURLResponse
5. blink: gets it with WebHTTPLoadInfo::setResponseHeadersText
6. blink's devtools agent reads that info: InspectorResourceAgent, buildObjectForResourceResponse
7. Then it gets to the front-end (m_frontend->responseReceived of that agent)

**Comment by jaredwilli** [comment]
This is a great post on contributing to chromium we should link to as well
http://meowni.ca/posts/chromium-101/

**Comment by Garbee** [comment]
Yea, that one is fantastic. Also really highlights the "you may need to search for related stuff" part of contributing since the codebase is so complex.

I'll be tackling this update (and conversion to HTML) after the console update is completed and merged.

**Comment by paulirish** [comment]
Another good post on understanding the flow of the frontend:
[What happens when DevTools Pauses](http://jasonlaster.github.io/js/devtools/2015/03/01/devtools-paused.html) by @jasonLaster

**Comment by paulirish** [comment]
## A Draft is born! 
https://docs.google.com/document/d/1WNF-KqRSzPLUUfZqQG5AFeU_Ll8TfWYcJasa_XGf7ro/edit# has already taken shape. More to come

**Comment by Garbee** [comment]
@pbakaus Once you are back from... that thing I can't remember... Can you drop your scripts into a gist and link it either here or in the draft doc? We are trying to collect as many useful scripts/aliases/tools for helping people out we can.

**Comment by paulirish** [comment]
http://oksoclap.com/p/r.339e25ef51d70c7bd8b4b668843be3d4 is the guide to DevTools tickets in the issue tracker. how they work, how to browse, how to subscribe

**Comment by pbakaus** [comment]
@Garbee see above, Gist already exists :)

**Comment by Garbee** [comment]
I saw that a while back. I was going to put off updating this until we know what is going on with the issue tracker itself as to not use time on that when it could be changing soon. However, with a bug push recently towards cleaning up the tracker internally I should probably go ahead and get this written up.

**Comment by Garbee** [comment]
[Quick outline](https://docs.google.com/document/d/177wfDVd5Za6NKOfe4ohQNEmeuF_zNXWzco059iXkTCc/edit) of what I'm thinking for the new structure.

**Comment by paulirish** [comment]
​nice. i think this is right on point.

**Comment by jasonLaster** [comment]
Looks good, maybe Ric and slack channels

**Comment by paulirish** [comment]
[Chrome DevTools Contribution Guide](https://docs.google.com/document/d/1WNF-KqRSzPLUUfZqQG5AFeU_Ll8TfWYcJasa_XGf7ro/edit#) is totally updated now.

**Comment by AnthumChris** [comment]
Found this link via DevTools Contrib Guide.  Would be nice to see instructions/recommendations in the Guide for reporting bugs or submitting feature requests related to DevTools.

**Comment by Garbee** [comment]
Reporting bugs is fairly straightforward, [crbug.com](https://crbug.com] and file a new issue. The wizard will walk you through everything.

Feature requests are trickier, since the wizard is "bug only" mentality. So you have to shove the feature request around the fields that the wizard asks for. We are trying to figure out the best way to guide better feature requests. Until that time, the best thing to do is hack it into the bugtracker wizard.
