### ISSUE TITLE
Automatic proofreading

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/devtools-docs#200]
I did a small research around automatic proofreading and found these two projects:

https://github.com/RobinvdVleuten/gingerbread , https://github.com/vesln/teacher - spelling
https://github.com/btford/write-good - Hemingway-app-like results

Basic test:
```
var gingerbread = require('gingerbread');
var writeGood = require('write-good');

var text = 'So the cat was stolen. The smelt of fliwers bring back memories.';

var suggestions = writeGood(text);

console.log('Hemingway-app-like suggestions:');
console.log(suggestions);

gingerbread(text, function (error, text, result, corrections) {
  console.log('Spelling: ');
  console.log(corrections);
});
```

Result:
```
Hemingway-app-like suggestions:
[ { index: 0, offset: 2, reason: '"So" adds no meaning' },
  { index: 11,
    offset: 10,
    reason: '"was stolen" is passive voice' } ]
Spelling: 
[ { text: 'smelt',
    correct: 'smell',
    definition: null,
    start: 27,
    length: 5 },
  { text: 'fliwers',
    correct: 'flowers',
    definition: 'a plant cultivated for its blooms or blossoms',
    start: 36,
    length: 7 },
  { text: 'bring',
    correct: 'brings',
    definition: null,
    start: 44,
    length: 5 } ]
```

Useful? Should I proceed with the research (I'd like to figure out how to hook it up to devtools docs)?

**Comment by bonog** [comment]
bonog

**Comment by Garbee** [comment]
/me hugs @kdzwinel.

Working [GREAT](https://travis-ci.org/GoogleChrome/devtools-docs/builds/50138042). This is fantastic work.

Closing this issue since the main task seems to be done. We can file issues either here and tag the appropriately or against the actual repo for the bot to handle anything else that may come up.

**Comment by paulirish** [comment]
yeah this is kind of magnificent.

**Comment by addyosmani** [comment]
Whoa. This is marvellous, @kdzwinel. We might try borrowing this for some of our other docs projects :)

**Comment by kdzwinel** [comment]
I'm glad you guys like it! Feel free to [borrow it](https://github.com/kdzwinel/Proofreader) :)

My only worry is number of false positives, but we will work it out. I've created a [short documentation in wiki](https://github.com/GoogleChrome/devtools-docs/wiki/Proofreader).
