### ISSUE TITLE
Comprehensive Keyboard Shortcuts

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#204]
So, we have a [feature request](https://code.google.com/p/chromium/issues/detail?id=441300) asking for a keyboard shortcut for the dock mode. In this we are trying to decide on a shortcut to use and I realized the [existing keyboard shortcuts](https://developer.chrome.com/devtools/docs/shortcuts) docs aren't very comprehensive. It looks as if they only point out the primary shortcuts or just the ones coded by the DevTools team/contributors and not any third-party resources like CodeMirror which we use for code editing.

Should we try to make this page more comprehensive and include things like CM shortcuts? This could be beneficial for people who don't know we are using CM and for figuring out what shortcuts are available in the future.

**Comment by jaredwilli** [comment]
#215 is the PR that includes this

**Comment by paulirish** [comment]
fixed  by #215
