### ISSUE TITLE
CodeMirror editing features

### ISSUE THREAD

**Issue by jaredwilli** [GoogleChrome/devtools-docs#209]
This is very related to #204

With CM4 and all that, we now have a bunch of editing features in the devtools.

Feels like we should summarize the editing experience?  

multiple cursors, select next occurrence, cmd / to comment, jump to previous location, all the languages we highlight for, 

there might be more:
https://github.com/mirrors/blink/commits/master/LayoutTests/inspector/editor
https://github.com/mirrors/blink/tree/master/LayoutTests/inspector/editor

and these https://twitter.com/_JayGeorge/status/453533491545001985

Currently we've got Ctrl-D support, 
Ctrl-U landed. 

Need to summarize the feature set we offer? might make for a blog post if its solid.

Here is the doc for this: https://docs.google.com/document/d/1yZRVR1X3UMy2OwxNHGo9zBFyoyRrUvnMw493BaEipT4/edit (currently collaborators only)

**Comment by jaredwilli** [comment]
@paulirish is this still necessary or can it be closed?

**Comment by Garbee** [comment]
We can go ahead and close this since the keyboard shortcuts are in which seem to be the main thing.

However, we should keep this in mind for the WF migration in case any of the new stuff needs documenting since there are some powerful upgrades with the CM4 upgrade that are most likely not in the current docs.

**Comment by Garbee** [comment]
cc @Meggin  Not sure how we want to track things to keep in mind for the WF migration. If you have something you should know about this. If not let me know and I can start a quick task list somewhere to integrate once we have some kind of public tracking.

**Comment by Meggin** [comment]
Jonathan-- quick task list in the repo sounds great! I can refer to this
task list as we start to build the new repo :). Can you let me know when
this is up? Thanks!

**Comment by Garbee** [comment]
Sure, I'll actually make an issue on this repo to list things out. Shouldn't be a big deal since the migration is already being talked about in public places.

**Comment by Garbee** [comment]
Issue #260 is the quick task list. We can add things as stuff comes up and later on move it to the migration repo as individual issues for assignment.

**Comment by Meggin** [comment]
Cool. Fast. Thanks.
