### ISSUE TITLE
Remove Elements Doc Page

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#221]
Completely overhaul [elements](https://developer.chrome.com/devtools/docs/elements) doc page. Horribly outdated.

--------

Due to discussion, now removing and forwarding to dom-and-styles.

**Comment by heatheramahan** [comment]
Wasn't that doc replaced by this one?
devtools/docs/dom-and-styles.html

So maybe we can just get rid of / archive devtools/docs/elements.html

**Comment by Garbee** [comment]
Ah yea, looks like dom-and-styles is a replacement for the elements page. So we can dump all of this and forward elements to dom-and-styles.

@paulirish Is this accurate?

**Comment by paulirish** [comment]
YUP!​

**Comment by paulirish** [comment]
fixed by #225
