### ISSUE TITLE
debugger-protocol docs throw internal error

### ISSUE THREAD

**Issue by kdzwinel** [GoogleChrome/devtools-docs#233]
https://developer.chrome.com/devtools/docs/debugger-protocol throws "Internal server error" . That's a first result when searching for "chrome debugging protocol".

BTW https://developer.chrome.com/devtools/docs redirects to https://developer.chrome.com/devtools/gsutil/third_party/python-gflags/debian/docs ?

**Comment by Garbee** [comment]
cc @Meggin @jpmedley since they were involved with figuring out the display issues from the other week which this may be related to (issue #216).

**Comment by paulirish** [comment]
fixed.
https://github.com/GoogleChrome/devtools-docs/commit/433b17a84324c3ca72fde670805682d127d9bcad
