### ISSUE TITLE
bug: heap contents demo broken

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/devtools-docs#235]
https://developer.chrome.com/devtools/docs/heap-profiling-containment

> https://developer.chrome.com/chrome-developer-tools/docs/heap-profiling-containment-files/script.js 
> Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Garbee** [comment]
Fixed by commit 5a68d2217bc22298c45ef775ade10d79a2ccc8e8
