### ISSUE TITLE
Helpful information for network timing

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#237]
I saw a [recent post](https://plus.google.com/+PaulIrish/posts/XBnyqXwgsua?pid=6101676468866457298&oid=114552443805676710515) from Ilya Grigorik that has an image describing a few timing situations and showing how the new network panel displays them up front. This kind of thing should be added to the docs. Showing how the network panel gets you these issues sooner, along with links on how to fix them. It should exist around the current content on network timing since it is directly related.

**Comment by Garbee** [comment]
Doing some other work in the network panel I realized this is already supposed to be documented under [waterfall view](https://developer.chrome.com/devtools/docs/network#waterfall-view).

**Comment by paulirish** [comment]
nice updates.
