### ISSUE TITLE
added CSS to element.style in the css tab sometimes not applied

### ISSUE THREAD

**Issue by brinkkemper** [GoogleChrome/devtools-docs#242]
I have an element with style="display: none;"
this has been set by js.
When inspecting this element and adjusting the element.style in the css tab of the devtools, the changes are not applied and reverted back when leaving the edit mode.

**Comment by Garbee** [comment]
1) To help people would need to see the actual code being run. If you could make a minimal example of the issue in a [codepen](http://codepen.io) then that would be great.

2) This is an issue tracker specifically for the *documentation* of the tools, not for support in using them or to report bugs with the tools itself. For support a [Chrome DevTools Google Group](https://groups.google.com/forum/#!forum/google-chrome-developer-tools) exists and for filing bugs against the tools directly [crbug](http://crbug.com/new) exists for tracking those.

**Comment by kdzwinel** [comment]
You can also try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/google-chrome-devtools) but please include some code (as Garbee already mentioned).
