### ISSUE TITLE
Preview tab is not showing rendered preview anymore

### ISSUE THREAD

**Issue by Pereitor** [GoogleChrome/devtools-docs#264]
Since a couple of updates ago, switching to the "Preview" tab in an ajax-gotten document is not showing the rendered content when it has HTML. That feature was very useful for debugging ajax-generated content, since you could take a look and see at a glance if everything was correct. In my case I'm using a debugger (x-debug) for the server generated content and it wraps every error, warning and exception in a table for visual formatting purposes. It's difficult to dive inside that bunch of html togs to find the actual error message. And even if you are not using a debugger, error messages can be difficult to find in they are hidden inside a block of html.

That feature was very useful and now and also we already had the "Response" tab, which is almost the same as "Preview" does but even better, as it has code formatting, turning the "Preview" one almost unuseful for me.

It would be of great help if the Preview tab returned to its previous functionality, displaying the rendered html contents
![previewtab](https://cloud.githubusercontent.com/assets/4677542/6686107/b51095ac-cc9f-11e4-8aa1-9e208eeaf6ab.png)
.

**Comment by kdzwinel** [comment]
Hey! This is Chrome DevTools *docs* repo, if you'd like to report a Chrome bug please do so on [crbug.com](http://crbug.com/new).

**Comment by Pereitor** [comment]
Aaargh! Going there; sorry for screwing it up.

**Comment by kdzwinel** [comment]
This looks like your bug: crbug.com/459554 . It's already fixed but probably not released to the stable Chrome yet. Meanwhile you can use Chrome Canary. Good luck!

**Comment by Pereitor** [comment]
Hey kdzwinel, you've been of great help! I was about to screw it again... I searched for the bug but didn't find it and was about to submit it. Thanks man! I promise to learn to search twice in the future :).

**Comment by Garbee** [comment]
Don't worry too much about accidentally submitting a duplicate bug in the code tracker. It is hard to search until you use it plenty. So long as you *try* to search first, we are happy. Since if you do find an existing bug, it saves us some time finding/remembering and merging things together.

**Comment by Pereitor** [comment]
Note taken, Garbee! Very kind and helpul answers indeed. And moreover: the bug is solved in Chrome Canary! Thanks again, dudes!
