### ISSUE TITLE
`dock to right` button is moved

### ISSUE THREAD

**Issue by arthurvr** [GoogleChrome/devtools-docs#271]
This sentence: https://github.com/GoogleChrome/devtools-docs/blob/116c99051c543d64703dd1371e380bd573431eee/docs/authoring-development-workflow.html#L36. It needs some updating as the button is moved. The screenshot is outdated as well.

**Comment by Garbee** [comment]
Let's just merge this over to issue #154. It was aimed to do this and then some.

I may even still have a branch with the changes started still on my repo....
