### ISSUE TITLE
Lost focus after press "F12"

### ISSUE THREAD

**Issue by BrodaNoel** [GoogleChrome/devtools-docs#275]
Hi all!
I lost the focus when I press F12 in Chrome.
For example:
I click on a User/pass input, press F12 and the focus is out.
Could you open the Devtools without change the focus?

See you guys!

**Comment by Garbee** [comment]
This tracker isn't for DevTools issues. It is for issues with our Documentation on [Developer.Chrome.Com](https://developer.chrome.com/devtools).

This is however a [bug already filed upstream](https://code.google.com/p/chromium/issues/detail?id=335477) that won't be fixed.

**Comment by BrodaNoel** [comment]
Won't be fixed? Wow... That is why I'm still using Firefox.
See you guys!
