### ISSUE TITLE
Undesired Result: Producing twice the indentation (or spaces)

### ISSUE THREAD

**Issue by djmtype** [GoogleChrome/devtools-docs#302]
When using workspaces and adding a new css style under the *Styles* tab, the result is saving twice the amount of indentation over to my stylesheet. Yet, under *Settings* I have 1 tab specified. The same can be said for specifying 2 spaces – the result would produce 4 spaces. This may seem minor, but if I was using `.sass` rather than `.css` or `.scss`, this might be problematic. In addition it just makes reading syntax harder to follow.

This issue seems to only affect selectors added via Chrome DevTools, not pre-existing selectors that already have at least one declaration attached to them. 

I've viewed my file in Sublime and Atom. Both editors display the same thing.

**Comment by djmtype** [comment]
Odd, now it's saving the indentation correctly.

**Comment by Garbee** [comment]
Please file technical issues as bugs against the DevTools on [crbug](http://crbug.com/new). This repository is for the documentation only (which has now even moved into WebFundamentals.)
