### ISSUE TITLE
Unable to remove folders from workspace under source tab in Developer Tools

### ISSUE THREAD

**Issue by akshay-sarkar** [GoogleChrome/devtools-docs#303]
Unable to remove folders from workspace under source tab in Developer Tools.

Earlier their seems to some options available to remove folder from workspace as per the [doc](https://developer.chrome.com/devtools/docs/workspaces).

Kindly provide a workaround for it.

**Comment by Garbee** [comment]
Seems to be working here.

Please file technical problems in the [Chromium issue tracker](https://crbug.com). That way they can be triaged and fixed if a problem is found.
