### ISSUE TITLE
Toggling FPS meter programmatically?

### ISSUE THREAD

**Issue by Dillybob92** [GoogleChrome/devtools-docs#304]
Hey guys,

I posted a question on StackOverflow [here](http://stackoverflow.com/questions/36013925/how-to-toggle-chromes-fps-meter-programmatically), and it looks like it's not possible?

I'm wondering if it's possible to enable the Show FPS meter in the Rendering tab on the dev console by Javascript? To toggle it on/off.

I am creating a nice action rpg game and would love, LOVE to know if this is possible. As I don't want my player's to open up the dev console, go to the rendering tab, etc.  

So, maybe this is a feature request, or maybe it's currently possible already? Thanks

**Comment by Garbee** [comment]
It is not possible nor will it be. DevTools operates in an isolated environment and individual bits of it can't be toggled on in web applications. It is up to developers to specifically enable this operation in the DevTools themselves to operate it.

There are other frame tools available as JavaScript packages you can include to use.

**Comment by Dillybob92** [comment]
Aww. Good point since it would only work if dev tools was enabled / open. Well, thanks for the response though :) I just love whoever worked on the graphics for the meter, it's very nice.
