### ISSUE TITLE
Add simple UX filter blur utility 

### ISSUE THREAD

**Issue by sorcamarian** [GoogleChrome/devtools-docs#312]
In Dev Tools when a HTML Node is focused and `H` key is pressed, that node gets hidden(`visibility: hidden !important`;)

I suggest adding a [CSS Filter](http://www.w3schools.com/cssref/css3_pr_filter.asp) blur (`-webkit-filter: blur(5px) `) on `B` `keypress` .

Blur value coulde be selected by pressing a number.
For example:
key: `B`  +  key: `9` => `-webkit-filter: blur(9px) `

In my case, [filter blur](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#blur()_2) is good for privacy, when I share a print screen.

**Comment by Garbee** [comment]
Please submit feature requests in the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list). This tracker is for the documentation only and the team that works on the software itself does not look here for work to do.

Thank you.
