### ISSUE TITLE
Link to chrome debugger protocol docs is outdated

### ISSUE THREAD

**Issue by coot** [GoogleChrome/devtools-docs#313]
The link in [here](https://github.com/GoogleChrome/devtools-docs/blob/master/docs/protocol/1.1/index.html) is outdated.

**Comment by paulirish** [comment]
thanks! updated in 9ddee238a92784047d94ee5aaf14ce77009013a0

**Comment by coot** [comment]
I am not sure where to report it but the link does not work in firefox (a blank page loads).

**Comment by paulirish** [comment]
which link?
