### ISSUE TITLE
How to export Java script code coverage result to a file, after running a java script application

### ISSUE THREAD

**Issue by Minarva-Siemens** [GoogleChrome/devtools-docs#318]
I want to get a statistic data after running a java script application. eg: total bytes covered, total unused bytes covered, percentage covered.

**Comment by Garbee** [comment]
This isn't currently supported in the DevTools. You'd need to file an issue on the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) for the engineers to triage and assess whether this feature should be added or not.

Thank you.
