### ISSUE TITLE
什么时候推出中文版本

### ISSUE THREAD

**Issue by zsio** [GoogleChrome/devtools-docs#327]
什么时候推出中文版本呢？     国人还是很多的。

**Comment by Garbee** [comment]
这些文档至少已部分用中文提供。 如果你去文档的新家。 然后滚动到页脚并从下拉列表中的选项中选择语言。 然后页面会更新，并显示翻译的内容。

-----

(Auto translated to Chinese (simplified) with Google translate. No idea if it is completely accurate.)

The docs are already, partially at least, available in Chinese. If you go to the new home of the docs. Then scroll to the footer and select the language from the options in the dropdown. The page then updates and what is translated is displayed.

The new home is back at [developers.google.com](https://developers.google.com/web/tools/chrome-devtools/).

**Comment by zsio** [comment]
Yes, thank you very much. But I am talking about the Chinese version of chrome devtools.
Is there a plan for this?

**Comment by paulirish** [comment]
There is currently no plan to localize the chrome devtools in Chinese. :( Sorry

**Comment by zsio** [comment]
It's ok, thank you very much for providing such a powerful tool.
@paulirish @Garbee 
Thank you very much.
