### ISSUE TITLE
Devtools "Workspace" and "Overrides" breaks file encoding

### ISSUE THREAD

**Issue by rusproject** [GoogleChrome/devtools-docs#332]
When file with Cyrillic (UTF-8) is opened with Chrome Devtools with "Local Overrides" enabled, all Cyrillic symbols transforms to unreadable abracadabra. I soon as I can see community [does know](https://bugs.chromium.org/p/chromium/issues/detail?id=596037) about this bug for years, but nobody cares. I have pretty much Cyrillic text in JS files (because of AJAX errors messages, and other things like that) but not too much to notice bug when I started working with Chrome Local Overrides Devtool.
So now I have a lot of broken files (code still working but not readable anymore) and a lot of git-commits containing abracadabra. I want to know if there is any way to fix this, because I tried every single encoding that is availabele in Notepad++, ST3 or Atom, and none of them helped.

Please share your ideas, if you need any additional info let me know. Thanks!

[example.zip](https://github.com/GoogleChrome/devtools-docs/files/4732818/example.zip)

here is the code if you can't download, but in ST3 editor it looks little bit different:
Normal code:
`$('example').innerHTML = 'Произошла ошибка!<br />Ваш ответ не был засчитан - попробуйте в следующий раз.<br />Спасибо!';
$('example').innerHTML = 'СПАСИБО!<br />Вы нам очень помогли!';
onFailure: function(transport)  { $('exetel-login-errors').update('Неизвестная ошибка'); }
onFailure: function(transport)  { $('vism-login-errors').update('Неизвестная ошибка'); }
$('navigation-loginv-errors').update('Неверный логин или пароль');
// 	ДЕЙСТВИЯ В РАСКРЫТОЙ КАРТОЧКЕ
// ПРЕВЬЮ
// ЗАКРЫТИЕ КАРТОЧКИ
`

After working with chrome DevTools Overrides or Workspaces (this happens not every time and not with with every file, for some reason):
`$('example').innerHTML = 'ÐÑÐ¾Ð¸Ð·Ð¾ÑÐ»Ð° Ð¾ÑÐ¸Ð±ÐºÐ°!<br />ÐÐ°Ñ Ð¾ÑÐ²ÐµÑ Ð½Ðµ Ð±ÑÐ» Ð·Ð°ÑÑÐ¸ÑÐ°Ð½ - Ð¿Ð¾Ð¿ÑÐ¾Ð±ÑÐ¹ÑÐµ Ð² ÑÐ»ÐµÐ´ÑÑÑÐ¸Ð¹ ÑÐ°Ð·.<br />Ð¡Ð¿Ð°ÑÐ¸Ð±Ð¾!';
$('example').innerHTML = 'Ð¡ÐÐÐ¡ÐÐÐ!<br />ÐÑ Ð½Ð°Ð¼ Ð¾ÑÐµÐ½Ñ Ð¿Ð¾Ð¼Ð¾Ð³Ð»Ð¸!';
onFailure: function(transport)  { $('exetel-login-errors').update('ÐÐµÐ¸Ð·Ð²ÐµÑÑÐ½Ð°Ñ Ð¾ÑÐ¸Ð±ÐºÐ°'); }
onFailure: function(transport)  { $('vism-login-errors').update('ÐÐµÐ¸Ð·Ð²ÐµÑÑÐ½Ð°Ñ Ð¾ÑÐ¸Ð±ÐºÐ°'); }
$('navigation-loginv-errors').update('ÐÐµÐ²ÐµÑÐ½ÑÐ¹ Ð»Ð¾Ð³Ð¸Ð½ Ð¸Ð»Ð¸ Ð¿Ð°ÑÐ¾Ð»Ñ');
// 	ÐÐÐÐ¡Ð¢ÐÐÐ¯ Ð Ð ÐÐ¡ÐÐ Ð«Ð¢ÐÐ ÐÐÐ Ð¢ÐÐ§ÐÐ
// ÐÐ ÐÐÐ¬Ð®
// ÐÐÐÐ Ð«Ð¢ÐÐ ÐÐÐ Ð¢ÐÐ§ÐÐ`

**Comment by Garbee** [comment]
@rusproject The best path is to file a new issue (as said in that thread.) The place to do that is https://crbug.com/new . File it against DevTools and it will be re-triaged and if needed prioritized. There is basically a whole new workflow in place with multiple companies working actively on the DevTools and priorities in various areas have shifted. However, they do not go through the archived issues looking for things.

This repository is about the previous home of the documentation (which has since been moved.) It is not the place to discuss bugs and addressing them with DevTools. That all happens on the Chromium Issue Tracker and discussion forums.

**Comment by rusproject** [comment]
@Garbee Thank you! I will do what you just said.
