### ISSUE TITLE
Screenshot sprint: T&T, Authoring, Memory Profiling

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/devtools-docs#44]
There have been a *lot* of changes made to the Canary DevTools since this doc was first authored. We currently have sections on..

* Console
* Timeline
* Sources
* Network
* Settings
* Profiles

Let's look at which shots are completely out of date and replace with retina.

Doc: https://developers.google.com/chrome-developer-tools/docs/tips-and-tricks

**Comment by paulirish** [comment]
iceboxing
