### ISSUE TITLE
Document DevTools extension API workarounds

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/devtools-docs#49]
Common asks from developers (braindump from my STP talk):

* Communicating between a panel, DevTools page and a bg page. Implied as the documentation says chrome.extension runtime APIs not available. Unfortunately, no alternatives offered.
* Better hooks for letting a framework augment rendered console objects. Allows you to differentiate between framework specific objects and meta-objects.
* It's not possible to execute XHRs from a DevTools page/panel. May be worth mentioning a background page could be used as a workaround.
* When is a script added or executed? Useful for extensions to know.
* Want to be able to inspect pseudo-elements/tree from an extension.
* Ability to create context-menus for extension panels more easily.
* Would like to be able to let a framework name anonymous functions.  Ideally with the extension enabled, displayName is used as a property for inferring the function name.
* Ability to change the context of the DevTools.
* Difficult to know why an action/function is being blocked rather than silently ignoring.
* Diagram of how to setup and structure a DevTools extension. Role of a DevTools page (panels, buttons, management) Communicating between different parts (pane, panel, background page)

**Comment by paulirish** [comment]
> * Communicating between a panel, DevTools page and a bg page. Implied as the documentation says chrome.extension runtime APIs not available. Unfortunately, no alternatives offered.

docs much better now

> * Better hooks for letting a framework augment rendered console objects. Allows you to differentiate between framework specific objects and meta-objects.

experiment now available.

see https://codereview.chromium.org/774903003/

> * When is a script added or executed? Useful for extensions to know.

No platform hooks, but agreed.

> * Would like to be able to let a framework name anonymous functions.  Ideally with the extension enabled, displayName is used as a property for inferring the function name.

displayName now supported

> * Diagram of how to setup and structure a DevTools extension. Role of a DevTools page (panels, buttons, management) Communicating between different parts (pane, panel, background page)

much better than 18mo ago.

**Comment by paulirish** [comment]
the rest are good but are on the feature request side of things. they'll have to end up in crbug.

cheers yall
